export const testDataWithoutTax = {
  id: 5490643992742,
  admin_graphql_api_id: "gid://shopify/Order/5490643992742",
  app_id: 580111,
  browser_ip: "2600:1700:2120:9f60:1cb9:42a5:30dd:ca8e",
  buyer_accepts_marketing: false,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: "Z2NwLXVzLXdlc3QxOjAxSFdZM045MFhIOVpOQTdKUlRCM05INVBW",
  checkout_id: 29637917016230,
  checkout_token: "568ea0948e5487d309732da3e3234c45",
  client_details: {
    accept_language: "en-US",
    browser_height: null,
    browser_ip: "2600:1700:2120:9f60:1cb9:42a5:30dd:ca8e",
    browser_width: null,
    session_hash: null,
    user_agent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15",
  },
  closed_at: null,
  confirmation_number: "G4YI880XG",
  confirmed: true,
  contact_email: "rsascampers@sbcglobal.net",
  created_at: "2024-05-02T16:22:42-10:00",
  currency: "USD",
  current_subtotal_price: "145.96",
  current_subtotal_price_set: {
    shop_money: { amount: "145.96", currency_code: "USD" },
    presentment_money: { amount: "145.96", currency_code: "USD" },
  },
  current_total_additional_fees_set: null,
  current_total_discounts: "0.00",
  current_total_discounts_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  current_total_duties_set: null,
  current_total_price: "145.96",
  current_total_price_set: {
    shop_money: { amount: "145.96", currency_code: "USD" },
    presentment_money: { amount: "145.96", currency_code: "USD" },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  customer_locale: "en-US",
  device_id: null,
  discount_codes: [],
  email: "rsascampers@sbcglobal.net",
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: "fulfilled",
  landing_site: "/?utm_source=sqmktg_email",
  landing_site_ref: null,
  location_id: null,
  merchant_of_record_app_id: null,
  name: "#3480",
  note: null,
  note_attributes: [],
  number: 2480,
  order_number: 3480,
  order_status_url:
    "https://www.bigislandrunningcompany.com/942962/orders/bb1c2bb29a1853f091070ac89e9d5bf7/authenticate?key=821a284e43c15790f1bfbdafa3df1a95",
  original_total_additional_fees_set: null,
  original_total_duties_set: null,
  payment_gateway_names: ["shopify_payments"],
  phone: null,
  po_number: null,
  presentment_currency: "USD",
  processed_at: "2024-05-02T16:22:36-10:00",
  reference: "20d252d3b97015a3aa4851005d83ea25",
  referring_site: "",
  source_identifier: "20d252d3b97015a3aa4851005d83ea25",
  source_name: "web",
  source_url: null,
  subtotal_price: "145.96",
  subtotal_price_set: {
    shop_money: { amount: "145.96", currency_code: "USD" },
    presentment_money: { amount: "145.96", currency_code: "USD" },
  },
  tags: "",
  tax_exempt: false,
  tax_lines: [],
  taxes_included: false,
  test: false,
  token: "bb1c2bb29a1853f091070ac89e9d5bf7",
  total_discounts: "0.00",
  total_discounts_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  total_line_items_price: "145.96",
  total_line_items_price_set: {
    shop_money: { amount: "145.96", currency_code: "USD" },
    presentment_money: { amount: "145.96", currency_code: "USD" },
  },
  total_outstanding: "0.00",
  total_price: "145.96",
  total_price_set: {
    shop_money: { amount: "145.96", currency_code: "USD" },
    presentment_money: { amount: "145.96", currency_code: "USD" },
  },
  total_shipping_price_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "USD" },
    presentment_money: { amount: "0.00", currency_code: "USD" },
  },
  total_tip_received: "0.00",
  total_weight: 0,
  updated_at: "2024-05-03T12:46:46-10:00",
  user_id: null,
  billing_address: {
    first_name: "Stephanie",
    address1: "1107 Hollydale Dr",
    phone: null,
    city: "Fullerton",
    zip: "92831",
    province: "California",
    country: "United States",
    last_name: "Wilmoth",
    address2: null,
    company: null,
    latitude: 33.8806426,
    longitude: -117.9048671,
    name: "Stephanie Wilmoth",
    country_code: "US",
    province_code: "CA",
  },
  customer: {
    id: 7774772527270,
    email: "rsascampers@sbcglobal.net",
    created_at: "2024-05-02T16:22:36-10:00",
    updated_at: "2024-05-02T16:22:43-10:00",
    first_name: "Stephanie",
    last_name: "Wilmoth",
    state: "disabled",
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    phone: null,
    email_marketing_consent: {
      state: "not_subscribed",
      opt_in_level: "single_opt_in",
      consent_updated_at: null,
    },
    sms_marketing_consent: null,
    tags: "",
    currency: "USD",
    tax_exemptions: [],
    admin_graphql_api_id: "gid://shopify/Customer/7774772527270",
    default_address: {
      id: 8764634300582,
      customer_id: 7774772527270,
      first_name: "Stephanie",
      last_name: "Wilmoth",
      company: null,
      address1: "1107 Hollydale Dr",
      address2: null,
      city: "Fullerton",
      province: "California",
      country: "United States",
      zip: "92831",
      phone: null,
      name: "Stephanie Wilmoth",
      province_code: "CA",
      country_code: "US",
      country_name: "United States",
      default: true,
    },
  },
  discount_applications: [],
  fulfillments: [
    {
      id: 4969143828646,
      admin_graphql_api_id: "gid://shopify/Fulfillment/4969143828646",
      created_at: "2024-05-03T12:46:46-10:00",
      location_id: 11808909,
      name: "#3480.1",
      order_id: 5490643992742,
      origin_address: {},
      receipt: {},
      service: "manual",
      shipment_status: null,
      status: "success",
      tracking_company: "USPS",
      tracking_number: "420928319305510570803154654067",
      tracking_numbers: [Array],
      tracking_url:
        "https://tools.usps.com/go/TrackConfirmAction_input?qtc_tLabels1=420928319305510570803154654067",
      tracking_urls: [Array],
      updated_at: "2024-05-03T12:46:46-10:00",
      line_items: [Array],
    },
  ],
  line_items: [
    {
      id: 13278219960486,
      admin_graphql_api_id: "gid://shopify/LineItem/13278219960486",
      current_quantity: 1,
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 0,
      name: "Women's Alii Tee - Short Sleeve - Kona - Classic Grey / M",
      price: "36.99",
      price_set: [Object],
      product_exists: true,
      product_id: 7937681653926,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: "LM7J3KB55OKQFDJEOFLXVVVY",
      taxable: true,
      title: "Women's Alii Tee - Short Sleeve",
      total_discount: "0.00",
      total_discount_set: [Object],
      variant_id: 44825369903270,
      variant_inventory_management: "shopify",
      variant_title: "Kona - Classic Grey / M",
      vendor: "Run Big",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 13278219993254,
      admin_graphql_api_id: "gid://shopify/LineItem/13278219993254",
      current_quantity: 1,
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 0,
      name: "Women's EZ-Tee - Long Sleeve - Run Big - Oil Teal / S",
      price: "39.99",
      price_set: [Object],
      product_exists: true,
      product_id: 7930351845542,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: "KXQHG53URJPRKABG44PUOVYS",
      taxable: true,
      title: "Women's EZ-Tee - Long Sleeve",
      total_discount: "0.00",
      total_discount_set: [Object],
      variant_id: 44831482871974,
      variant_inventory_management: "shopify",
      variant_title: "Run Big - Oil Teal / S",
      vendor: "rabbit x Run Big",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 13278220026022,
      admin_graphql_api_id: "gid://shopify/LineItem/13278220026022",
      current_quantity: 1,
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 0,
      name: "Men's Infinity Tee - LS - Run Big - Navy / M",
      price: "39.99",
      price_set: [Object],
      product_exists: true,
      product_id: 7936684654758,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: "DIYG32UMYFQA7OVEXJP75IHV",
      taxable: true,
      title: "Men's Infinity Tee - LS",
      total_discount: "0.00",
      total_discount_set: [Object],
      variant_id: 44823082533030,
      variant_inventory_management: "shopify",
      variant_title: "Run Big - Navy / M",
      vendor: "Run Big",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 13278220058790,
      admin_graphql_api_id: "gid://shopify/LineItem/13278220058790",
      current_quantity: 1,
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 0,
      name: "Elite Running Hat - Run Big - Black/Blue",
      price: "28.99",
      price_set: [Object],
      product_exists: true,
      product_id: 7928150524070,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: "6XSLCP2PDNQRMON2KGM6MIHR",
      taxable: true,
      title: "Elite Running Hat",
      total_discount: "0.00",
      total_discount_set: [Object],
      variant_id: 44802880962726,
      variant_inventory_management: "shopify",
      variant_title: "Run Big - Black/Blue",
      vendor: "BOCO x Run Big",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
  ],
  payment_terms: null,
  refunds: [],
  shipping_address: {
    first_name: "Stephanie",
    address1: "1107 Hollydale Dr",
    phone: null,
    city: "Fullerton",
    zip: "92831",
    province: "California",
    country: "United States",
    last_name: "Wilmoth",
    address2: null,
    company: null,
    latitude: 33.8806426,
    longitude: -117.9048671,
    name: "Stephanie Wilmoth",
    country_code: "US",
    province_code: "CA",
  },
  shipping_lines: [
    {
      id: 4537597788326,
      carrier_identifier: "650f1a14fa979ec5c74d063e968411d4",
      code: "USPS Priority",
      discounted_price: "0.00",
      discounted_price_set: [Object],
      is_removed: false,
      phone: null,
      price: "0.00",
      price_set: [Object],
      requested_fulfillment_service_id: null,
      source: "shopify",
      title: "USPS Priority",
      tax_lines: [],
      discount_allocations: [],
    },
  ],
};

export const testDataWithTax = {};
